import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar, { WhatsAppStickyButton } from '../components/Navbar';
import Footer from '../components/Footer';
import NavbarProvider from '../context/NavbarContext';
import { AuthProvider } from '../context/AuthContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/logo.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#121212] text-white`}
      >
        <AuthProvider>
          <NavbarProvider>
            <Navbar />
            {children}
            <Footer />
          </NavbarProvider>
        </AuthProvider>
        <WhatsAppStickyButton />
      </body>
    </html>
  );
}
